src/Subastas/Subastas/Controllers/LogEntriesController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Abstractions;
using Subastas.Interfaces.Repositories;

namespace Subastas.Controllers
{
    public class LogEntriesController : Controller
    {
        private readonly ILogEntryRepository _repository;

        public LogEntriesController(ILogEntryRepository repository)
        {
            _repository = repository;
        }

        // GET: LogEntries
        public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 10)
        {
            if (pageNumber < 1)
            {
                pageNumber = 1;
            }

            var logs = await _repository.GetAllLogsAsync(pageNumber, pageSize);
            var totalLogs = await _repository.GetTotalLogsCountAsync();

            ViewBag.PageNumber = pageNumber;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalLogs = totalLogs;

            return View(logs);
        }

        public async Task<IActionResult> Details(int id)
        {
            var log = await _repository.GetLogByIdAsync(id);
            if (log == null)
            {
                return NotFound();
            }
            return View(log);
        }
    }
}

src/Subastas/Subastas/Controllers/SubastaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using Subasta.Managers;
using Subastas.Interfaces;
using Subastas.Interfaces.Services;
using System.Data.Common;
using Microsoft.AspNetCore.Http;
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Drawing.Charts;
using Newtonsoft.Json;
using static Amazon.Runtime.Internal.Settings.SettingsCollection;
using System.Drawing.Printing;
using System.Text;
using Subastas.Services;
using Subastas.Domain;
using DocumentFormat.OpenXml.Spreadsheet;

namespace Subastas.Controllers
{
    [Authorize(AuthenticationSchemes = "Bearer")]
    public class SubastaController : Controller
    {
        private readonly IProductoService _productoService;
        private readonly ISubastaService _subastaService;
        private readonly IUserService _userService;
        private readonly IHubContext<SubastaHub> _hubContext;

        public SubastaController(
            IProductoService productoService,
            ISubastaService subastaService,
            IUserService userService,
            IHubContext<SubastaHub> hubContext)
        {
            _productoService = productoService;
            _subastaService = subastaService;
            _userService = userService;
            _hubContext = hubContext as IHubContext<SubastaHub>; // Conversión explícita
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                IEnumerable<Domain.Subasta> listaSubasta;

                if (User.IsInRole("Admin"))
                {
                    listaSubasta = await _subastaService.GetCollectionByPredicateWithIncludesAsync(s => s.EstaActivo || !s.EstaActivo, x => x.Pujas);
                }
                else
                {
                    listaSubasta = await _subastaService.GetCollectionByPredicateWithIncludesAsync(s => s.EstaActivo, x => x.Pujas);
                }

                // Para cada subasta en la lista
                foreach (var subasta in listaSubasta)
                {
                    if (subasta.Pujas.Any())
                    {
                        var ultimaPuja = subasta.Pujas.OrderByDescending(p => p.FechaPuja).First();

                        subasta.MontoInicial = ultimaPuja.MontoPuja;
                    }
                    else
                    {
                        subasta.MontoInicial = 0;
                    }
                }

                listaSubasta = await _subastaService.SetToListProductoWithImgPreloaded(listaSubasta.ToList());
                return View(listaSubasta);
            }
            catch (DbException ex)
            {
                // TODO EVENTLOGEOLOGEOSO PERRASSSSSS
                ModelState.AddModelError(string.Empty, "Error de base de datos: " + ex.Message);
                return View();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Ocurrió un error: " + ex.Message);
                return View();
            }
        }

        [Authorize(AuthenticationSchemes = "Bearer", Roles ="Admin")]
        public async Task<IActionResult> Create()
        {
            ViewData["IdProducto"] = new SelectList(await _productoService.GetAllByPredicateAsync(p => !p.EstaSubastado && p.EstaActivo && p.Subasta.IdProducto != p.IdProducto), "IdProducto", "NombreProducto");
            return View(new Domain.Subasta());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(AuthenticationSchemes = "Bearer", Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("TituloSubasta,MontoInicial,FechaSubasta,FechaSubastaFin,IdProducto")] Domain.Subasta subasta)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _hubContext.Clients.All.SendAsync("ReceiveSubastaUpdate");
                    await _subastaService.CreateAsync(subasta);
                    return RedirectToAction(nameof(Index));
                }

                ViewData["IdProducto"] = new SelectList(await _productoService.GetAllByPredicateAsync(p => !p.EstaSubastado && p.EstaActivo && p.Subasta.IdProducto != p.IdProducto), "IdProducto", "NombreProducto");
            }
            catch (Exception ex)
            {
                // LogError
            }

            return View(subasta);
        }

        [Authorize(AuthenticationSchemes = "Bearer")]
        public async Task<IActionResult> Details(int id)
        {
            var subasta = new Domain.Subasta();
            try
            {
                subasta = await _subastaService.GetSubastaWithPujaAndUsers(id) ?? subasta;
                subasta = await _subastaService.SetProductoWithImgPreloaded(subasta);

                if (subasta != null)
                {
                    decimal? maxMontoPuja = subasta.Pujas.Any() ? (decimal?)subasta.Pujas.Max(s => s.MontoPuja) : null;
                    ViewBag.MaxMontoPuja = maxMontoPuja;

                    if (maxMontoPuja.HasValue)
                    {
                        // Obtener el IdUsuario correspondiente al monto de puja más alto
                        int idUsuarioMaxPuja = subasta.Pujas.First(p => p.MontoPuja == maxMontoPuja).IdUsuario;

                        // Obtener el nombre del usuario con el IdUsuario encontrado
                        var usuarioConMaxPuja = await _userService.GetByIdAsync(idUsuarioMaxPuja);
                        ViewBag.NombreUsuarioMaxPuja = usuarioConMaxPuja.NombreUsuario;
                    }
                }
                return View(subasta);
            }
            catch (Exception)
            {
                return View(subasta);
            }
        }


        [Authorize(AuthenticationSchemes = "Bearer", Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var subasta = await _subastaService.GetByIdAsync(id);
            if (subasta == null)
            {
                 return RedirectToAction(nameof(Index));
            }

            ViewData["IdProducto"] = new SelectList(await _productoService.GetAllByPredicateAsync(p => !p.EstaSubastado && p.EstaActivo && (p.Subasta.IdProducto != p.IdProducto || p.Subasta.IdSubasta == id)), "IdProducto", "NombreProducto", subasta.IdProducto);
            return View("Create", subasta);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(AuthenticationSchemes = "Bearer", Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("IdSubasta,TituloSubasta,MontoInicial,FechaSubasta,FechaSubastaFin,IdProducto,EstaActivo,Finalizada")] Domain.Subasta subasta)
        {
            if (id != subasta.IdSubasta)
            {
                 return RedirectToAction(nameof(Index));
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _hubContext.Clients.All.SendAsync("ReceiveSubastaUpdate");
                    await _subastaService.UpdateAsync(subasta);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    // LogError
                }
            }

            ViewData["IdProducto"] = new SelectList(await _productoService.GetAllByPredicateAsync(p => !p.EstaSubastado && p.EstaActivo && (p.Subasta.IdProducto != p.IdProducto || p.Subasta.IdSubasta == id)), "IdProducto", "NombreProducto", subasta.IdProducto);
            return View("Create", subasta);
        }


        [HttpPost]
        [Authorize(AuthenticationSchemes = "Bearer")]
        public async Task<IActionResult> Delete(int id)
        {
            var result = new { success = false, errorMessage = "" };

            try
            {
                var subasta = await _subastaService.GetSubastaWithPujaAndUsers(id);

                var usersPujas = subasta.Pujas
                    .GroupBy(p => p.IdUsuario)
                    .Select(g => new
                    {
                        UserId = g.Key,
                        SumaDePujas = g.Sum(p => p.MontoPuja)
                    })
                    .ToList();

                var deleted = await _subastaService.DeleteById(id);

                if (deleted)
                {
                    foreach (var user in usersPujas)
                    {
                        var usuario = await _userService.GetUserWithCuentum(user.UserId);

                        usuario.Cuentum.Saldo += user.SumaDePujas;

                        await _userService.UpdateAsync(usuario);
                    }

                    await _hubContext.Clients.All.SendAsync("ReceiveSubastaUpdate");
                    result = new { success = true, errorMessage = "" };
                }
                else
                {
                    result = new { success = false, errorMessage = "Parece que hubo un error" };
                }
            }
            catch (Exception ex)
            {
                result = new { success = false, errorMessage = ex.Message };
            }

            return Json(result);
        }

        [HttpPost]
        public async Task<IActionResult> TerminarSubasta(int idSubasta)
        {
            try
            {
                var subasta = await _subastaService.GetSubastaWithPujaAndUsers(idSubasta);

                if (subasta == null)
                {
                    return NotFound();
                }

                subasta.EstaActivo = false;
                var ganador = subasta.Pujas.OrderByDescending(p => p.MontoPuja).FirstOrDefault()?.IdUsuarioNavigation;

                if (ganador == null)
                {
                    return NotFound();
                }

                subasta.IdUsuario = ganador.IdUsuario;

                await _subastaService.UpdateAsync(subasta);

src/Subastas/Subastas/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Subastas.styles.css" asp-append-version="true" />
    <!-- SweetAlert2 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@10/dist/sweetalert2.min.css" rel="stylesheet">
    <!-- FontAwesome CSS -->
    <link href="~/css/fontawesome/all.css" rel="stylesheet" />
    <link href="~/css/fontawesome/all.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-primary" asp-area="" asp-controller="Subasta" asp-action="Index">
                    <img src="~/assets/img/megasubastasLogo.png" height="50px"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="subastasDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Subastas
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="subastasDropdown">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Subasta" asp-action="Index">Listar</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Subasta" asp-action="Create">Crear</a></li>
                                </ul>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="productoDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Producto
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="productoDropdown">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Producto" asp-action="Index">Listar</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Producto" asp-action="Create">Crear</a></li>
                                </ul>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="usuarioDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Usuario
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="usuarioDropdown">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Usuario" asp-action="Index">Listar</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Usuario" asp-action="Create">Crear</a></li>
                                </ul>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="usuarioDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Logs
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="usuarioDropdown">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="LogEntries" asp-action="Index">Listar</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (!string.IsNullOrEmpty(User.FindFirstValue(ClaimTypes.NameIdentifier)))
                            {
                                <li class="nav-item d-flex align-items-center me-2">
                                    <a class="nav-link" asp-controller="Usuario" asp-action="Details" asp-route-id="@User.FindFirstValue(ClaimTypes.NameIdentifier)">
                                        @User.FindFirstValue(ClaimTypes.Name)
                                    </a>
                                </li>
                            }

                            <li class="nav-item">
                                <form asp-controller="Authentication" asp-action="Logout" method="post" class="form-inline">
                                    <button type="submit" class="btn btn-outline-dark">Logout</button>
                                </form>
                            </li>
                        }
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Subastas - <a href="https://github.com/lrivas3/Subastas" target="_blank">Repo</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- SweetAlert2 JS -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- FontAwesome JS -->
    <script src="~/js/fontawesome/all.js"></script>
    <script src="~/js/fontawesome/all.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Subastas/Subastas/Views/Shared/_authLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Subastas.styles.css" asp-append-version="true" />
    <link href="~/css/AuthController.css" rel="stylesheet">
</head>
<body class="bg-light d-flex justify-content-center align-items-center" style="height: 50vh;">
    <div class="p-4 card container mt-5">
        @RenderBody()
    </div>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>