src/Subastas/Subastas/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Subastas.Domain;
using Subastas.Dto.Producto;
using Subastas.Interfaces;
using Microsoft.AspNetCore.Http;
using Subastas.Interfaces.Services;
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Drawing.Charts;
using Newtonsoft.Json;
using static Amazon.Runtime.Internal.Settings.SettingsCollection;
using System.Drawing.Printing;
using System.Text;

namespace Subastas.Controllers
{
    [Authorize(AuthenticationSchemes = "Bearer", Roles = "Admin")]
    public class ProductoController : Controller
    {
        private readonly IProductoService _productoService;
        private readonly ILogger<ProductoController> _logger;

        public ProductoController(IProductoService productoService)
        {
            _productoService = productoService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var listaProductos = await _productoService.GetAllWithImageUrlsAsync();
                return View(listaProductos);
            }
            catch (Exception ex)
            {
                ViewData["Error"] = "An error occurred while trying to retrieve the products.";
                _logger.LogError(ex, "An error occurred while trying to retrieve the products.");
                return View();
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NombreProducto,DescripcionProducto,EstaActivo")] ProductoCreateRequest productoRequest, IFormFile imagen)
        {
            if (!ModelState.IsValid)
            {
                return View(productoRequest);
            }

            try
            {
                var newProducto = await _productoService.CreateWithImageAsync(productoRequest, imagen);
                if (newProducto == null)
                {
                    throw new Exception("Product creation failed.");
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                
                return View(productoRequest);
            }
        }
        
        
        // GET: Producto/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _productoService.GetByIdWithImageUrlAsync(id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }
        
        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var success = await _productoService.SoftDeleteAsync(id);
            if (success)
            {
                return RedirectToAction(nameof(Index));
            }
            ModelState.AddModelError("", "Failed to delete the product.");
            return RedirectToAction(nameof(Index));
        }
        
        // GET: Producto/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var producto = await _productoService.GetByIdWithImageUrlAsync(id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }
        
        
        // GET: Producto/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var producto = await _productoService.GetByIdWithImageUrlAsync(id);
            if (producto == null)
            {
                return NotFound();
            }

            // Aquí podrías realizar alguna transformación de datos si es necesario antes de enviarlos a la vista de edición
            return View(producto);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProductoCreateRequest productoToUpdate, IFormFile imagen)
        {
            if (!ModelState.IsValid)
            {
                var productoToReturn = await _productoService.GetByIdAsync(id);
                if (productoToReturn == null)
                {
                    return NotFound();
                }
                // Map properties manually or use a mapper to transfer data
                productoToReturn.NombreProducto = productoToUpdate.NombreProducto;
                productoToReturn.DescripcionProducto = productoToUpdate.DescripcionProducto;
                productoToReturn.EstaActivo = productoToUpdate.EstaActivo;

                return View(productoToReturn);
            }

            try
            {
                var updatedProducto = await _productoService.UpdateWithImageAsync(id, productoToUpdate, imagen);
                if (updatedProducto == null)
                {
                    throw new Exception("Failed to update the product.");
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                var productoToReturn = await _productoService.GetByIdAsync(id);
                
                return View(productoToReturn);
            }
        }

        public async Task<IActionResult> Export(string format)
        {
            List<ProductoExportModel> productos;

            try
            {
                productos = (await _productoService.GetAllAsync())
                                .Where(p => p.EstaActivo)
                                .Select(p => new ProductoExportModel
                                {
                                    Nombre = p.NombreProducto,
                                    Descripcion = p.DescripcionProducto,
                                    Activo = p.EstaActivo ? "Sí" : "No",
                                    Subastado = p.EstaSubastado ? "Sí" : "No"
                                })
                                .ToList();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error al obtener los productos: {ex.Message}");
                
                return StatusCode(500, "Error al obtener los productos");
            }

            if (productos == null || !productos.Any())
            {
                return NotFound("No hay productos para exportar.");
            }

            if (format == "xlsx")
            {
                byte[] fileContents;
                try
                {
                    using (var workbook = new XLWorkbook())
                    {
                        var worksheet = workbook.Worksheets.Add("Productos");
                        worksheet.Cell(1, 1).Value = "Nombre";
                        worksheet.Cell(1, 2).Value = "Descripción";
                        worksheet.Cell(1, 3).Value = "Activo";
                        worksheet.Cell(1, 4).Value = "Subastado";

                        int row = 2;
                        foreach (var producto in productos)
                        {
                            worksheet.Cell(row, 1).Value = producto.Nombre;
                            worksheet.Cell(row, 2).Value = producto.Descripcion;
                            worksheet.Cell(row, 3).Value = producto.Activo;
                            worksheet.Cell(row, 4).Value = producto.Subastado;
                            row++;
                        }

                        using (var stream = new MemoryStream())
                        {
                            workbook.SaveAs(stream);
                            fileContents = stream.ToArray();
                        }
                    }

                    return File(fileContents, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "productos.xlsx");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Error al generar el archivo Excel: {ex.Message}");
                    
                    return StatusCode(500, "Error al generar el archivo Excel");
                }
            }
            else if (format == "json")
            {
                try
                {
                    var json = JsonConvert.SerializeObject(productos, Newtonsoft.Json.Formatting.Indented);
                    var jsonBytes = Encoding.UTF8.GetBytes(json);

                    return File(jsonBytes, "application/json", "productos.json");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Error al generar el archivo JSON: {ex.Message}");
                    
                    return StatusCode(500, "Error al generar el archivo JSON");
                }
            }

            return NotFound();
        }

        public class ProductoExportModel
        {
            public string Nombre { get; set; }
            public string Descripcion { get; set; }
            public string Activo { get; set; }
            public string Subastado { get; set; }
        }

    }
}

src/Subastas/Subastas/Views/Producto/Create.cshtml
@model Subastas.Dto.Producto.ProductoCreateRequest

@{
    ViewData["Title"] = "Crear Producto";
}

<div class="create">
    <div class="justify-content-left btn-return">
        <img src="/assets/img/icons/returnIcon.png" alt="Regresar" height="40px">
        <a asp-action="Index">Regresar</a>
    </div>
    <br/>
    <h1>Crear Producto</h1>

    <div class="row">
        <div class="col-md-6">
            <form asp-action="Create" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="NombreProducto" class="control-label"></label>
                    <input asp-for="NombreProducto" class="form-control" />
                    <span asp-validation-for="NombreProducto" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DescripcionProducto" class="control-label"></label>
                    <textarea asp-for="DescripcionProducto" class="form-control"></textarea>
                    <span asp-validation-for="DescripcionProducto" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="imagen" class="control-label">Imagen Producto</label>
                    <input type="file" class="form-control" id="imagen" name="imagen" required />
                    <span class="text-danger" data-valmsg-for="imagen" data-valmsg-replace="true"></span>
                </div>
                <div class="form-group">
                    <div class="form-check">
                        <input asp-for="EstaActivo" class="form-check-input" />
                        <label asp-for="EstaActivo" class="form-check-label"></label>
                    </div>
                    <span asp-validation-for="EstaActivo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Crear" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/Subastas/Subastas/Views/Producto/Delete.cshtml
@model Subastas.Domain.Producto
@{
    ViewData["Title"] = "Delete";
}

<div class="create">
    <div class="justify-content-left btn-return">
        <img src="/assets/img/icons/returnIcon.png" alt="Regresar" height="40px">
        <a asp-action="Index">Regresar</a>
    </div>
    <br />

    <h1>Eliminar Producto</h1>
    <h3>¿Seguro que quiere eliminar este producto?</h3>
    <br />
    <div>
        <dl class="dl-horizontal">
            <dt>Nombre</dt>
            <dd>@Model.NombreProducto</dd>

            <dt>Descripción</dt>
            <dd>@Model.DescripcionProducto</dd>

            <!-- Verificación y muestra de la imagen del producto -->
            @if (!string.IsNullOrEmpty(Model.ImagenProducto))
            {
                <dt>Imagen</dt>
                <dd><img src="@Model.ImagenProducto" alt="Imagen del Producto" style="max-width: 100%; max-height: 300px;"></dd>
            }
            else
            {
                <dt>Imagen</dt>
                <dd>No disponible</dd>
            }
        </dl>
    
        <form asp-action="DeleteConfirmed" method="post">
            @Html.AntiForgeryToken()
            <input type="hidden" name="id" value="@Model.IdProducto" />
            <input type="submit" value="Eliminar" class="btn btn-danger" />
        </form>
    </div>
</div>

src/Subastas/Subastas/Views/Producto/Details.cshtml
@model Subastas.Domain.Producto

@{
    ViewBag.Title = "Listado de Productos";
    Layout = "_Layout";
}

<div class="create">
    <div class="justify-content-left btn-return">
        <img src="/assets/img/icons/returnIcon.png" alt="Regresar" height="40px">
        <a asp-action="Index">Regresar</a>
    </div>
    <br />
    <h1>Detalles del Producto</h1>
    <div>
        <dl class="dl-horizontal">
            <dt>ID</dt>
            <dd>@Model.IdProducto</dd>

            <dt>Nombre</dt>
            <dd>@Model.NombreProducto</dd>

            <dt>Descripción</dt>
            <dd>@Model.DescripcionProducto</dd>

            <dt>Estado</dt>
            @if(Model.EstaActivo)
            {
                <dd>Activo</dd>
            }
            else
            {
                <dd>Inactivo</dd>
            }

            <!-- Verificación y muestra de la imagen del producto -->
            @if (!string.IsNullOrEmpty(Model.ImagenProducto))
            {
                <dt>Imagen</dt>
                <dd><img src="@Model.ImagenProducto" alt="Imagen del Producto" style="max-width: 100%; max-height: 300px;"></dd>
            }
            else
            {
                <dt>Imagen</dt>
                <dd>No disponible</dd>
            }
        </dl>
    </div>
</div>

src/Subastas/Subastas/Views/Producto/Edit.cshtml
@model Subastas.Domain.Producto

@{
    ViewBag.Title = "Editar Producto";
    Layout = "_Layout";
}

<div class="create">
    <div class="justify-content-left btn-return">
        <img src="/assets/img/icons/returnIcon.png" alt="Regresar" height="40px">
        <a asp-action="Index">Regresar</a>
    </div>
    <br />
    <h1>@ViewBag.Title</h1>

    <form asp-action="Edit" asp-controller="Producto" method="post" enctype="multipart/form-data">
        @Html.AntiForgeryToken()

        <input type="hidden" name="id" value="@Model.IdProducto" />

        <div class="form-group">
            <label asp-for="NombreProducto" class="control-label"></label>
            <input asp-for="NombreProducto" class="form-control" />
            <span asp-validation-for="NombreProducto" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="DescripcionProducto" class="control-label"></label>
            <textarea asp-for="DescripcionProducto" class="form-control"></textarea>
            <span asp-validation-for="DescripcionProducto" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="EstaActivo" class="control-label"></label>
            <select asp-for="EstaActivo" class="form-control">
                <option value="true">Activo</option>
                <option value="false">Inactivo</option>
            </select>
            <span asp-validation-for="EstaActivo" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label for="imagen" class="control-label">Imagen Actual</label>
            <div>
                @if (Model.ImagenProducto != null)
                {
                    <img src="@Model.ImagenProducto" alt="Imagen del Producto" style="max-height: 200px; display: block; margin-bottom: 10px;" />
                }
            </div>
            <label for="imagen" class="control-label">Seleccionar nueva imagen (opcional):</label>
            <input type="file" name="imagen" class="form-control" />
        </div>

        <div class="form-group">
            <input type="submit" value="Guardar cambios" class="btn btn-success" />
            <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
        </div>
    </form>
</div>

src/Subastas/Subastas/Views/Producto/Index.cshtml
@model IEnumerable<Subastas.Domain.Producto>

@{
    ViewData["Title"] = "Productos";
    bool isAdmin = User.IsInRole("Admin");
}

@if (isAdmin)
{
    <div class="dropdown">
        <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
            Exportar reporte
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li><a class="dropdown-item" href="#" onclick="exportTo('xlsx')"><img src="~/assets/img/icons/ExcelIcon.png" height="20px" style="margin-right: 10px;"/>EXCEL</a></li>
            <li><a class="dropdown-item" href="#" onclick="exportTo('json')"><img src="~/assets/img/icons/JSONIcon.png" height="20px" style="margin-right: 10px;" />JSON</a></li>
        </ul>
    </div>
    <br />
}

<link rel="stylesheet" href="~/css/SubastasIndex.css" asp-append-version="true" />

<div class="row row-cols-1 row-cols-md-5 g-4">
    @if (Model == null || !Model.Any())
    {
        <div class="col">
            <h1>¡Parece que no hay Productos!</h1>
        </div>
    }
    else
    {
        @foreach (var item in Model)
        {
            <div class="col">
                <div class="card h-100">
                    <a href="@Url.Action("Details", new { id = item.IdProducto })" class="text-decoration-none text-dark">
                        <img src="@(!string.IsNullOrEmpty(item.ImagenProducto) ? item.ImagenProducto : "https://www.cruiseloloma.co.nz/wp-content/uploads/2014/12/placeholder-400x300.jpg")"
                             class="card-img-top img-fixed-size" alt="@item.NombreProducto">
                        <div class="card-body">
                            <h5 class="card-title">@item.NombreProducto</h5>
                            <p class="card-text">@item.DescripcionProducto</p>
                            <div class="@(item.EstaActivo ? "bg-active" : "bg-inactive") card-text">
                                Activo: @(item.EstaActivo ? "Sí" : "No")
                            </div>
                            <div class="@(item.EstaSubastado ? "bg-active" : "bg-inactive") card-text">
                                Subastado: @(item.EstaSubastado ? "Sí" : "No")
                            </div>
                        </div>
                    </a>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <div class="card-footer text-center">
                            <a href="@Url.Action("Details", new { id = item.IdProducto })" class="btn btn-secondary text-white mx-2">Detalles</a>
                            <a href="@Url.Action("Edit", new { id = item.IdProducto })" class="btn btn-primary text-white mx-2">Editar</a>
                            <a href="@Url.Action("Delete", new { id = item.IdProducto })" class="btn btn-danger text-white mx-2">Eliminar</a>
                        </div>
                    }
                </div>
            </div>
        }
    }
</div>

@section Scripts {
    <script>
        async function exportTo(format) {
            try {
                var exportUrl = '@Url.Action("Export", "Producto")' + '?format=' + format;

                const response = await fetch(exportUrl);
                if (!response.ok) {
                    throw new Error('Explotó D:');
                }

                const blob = await response.blob();

                // Obtener la fecha y hora actual
                const dateTime = new Date();
                const formattedDateTime = dateTime.toLocaleString('en-US', {
                    year: 'numeric',
                    month: '2-digit',
                    day: '2-digit',
                    hour: '2-digit',
                    minute: '2-digit',
                    second: '2-digit',
                    hour12: true
                }).replace(/:/g, '_').replace(/\s/g, ' ');

                // Construir el nombre del archivo con la fecha y hora
                const fileName = 'Productos_export_' + formattedDateTime + '.' + format;

                const downloadUrl = window.URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = downloadUrl;
                a.download = fileName; // Usar el nuevo nombre del archivo
                document.body.appendChild(a);
                a.click();
                a.remove();
                window.URL.revokeObjectURL(downloadUrl);

                console.log("Exportando a " + format);
            } catch (error) {
                console.error('Error exportando el archivo:', error);
            }
        }
    </script>
}